### ISSUE TITLE
Small optimisation issue

### ISSUE THREAD

**Issue by rdebath** [ScoreUnder/brainfuck-interpreter#1]
This _should_ print `Hello World!` not `Helr World!`

``` BF
    [-]>[-]++++++++[<+++++++++>-]<.>+++++[<+++++>-]<++++.
    +++++++.><.+++.
    [-]

    >+++++++[<++++>-]<+[>++++>+++>+<<<-]>>>+++.<.<-----.+
    ++.------.--------.>>+.>++++++++++.[>]<[[-]<]
```

**Comment by ScoreUnder** [comment]
Interesting! Thanks for the report, I suspected I'd missed something like this.

Compiling a debug build (`make -B CPPFLAGS=`) shows an assertion failing. I can trigger the same assertion failure with this code:

`><`

Wrapping the code in `+[- etc etc [-]]` stops the problem from occurring, but that's a hack.

I think I know where the problem lies - the `flattener` makes some dangerous-ish assumptions that the code has already been run through the `optimizer`, but the outermost body of code doesn't ever get passed through the optimizer.

Let's see if I can't fix this...
